"""initial application schema

Revision ID: fe7d184ad42b
Revises:
Create Date: 2026-07-28 23:31:39.355241
"""

from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

revision: str = "fe7d184ad42b"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None

RLS_TABLES = (
    "ai_actions",
    "ai_batch_items",
    "ai_batch_jobs",
    "ai_chats",
    "ai_conversations",
    "ai_messages",
    "ai_tool_calls",
    "care_events",
    "care_schedules",
    "device_tokens",
    "diagnoses",
    "diagnosis_images",
    "media_files",
    "monthly_reports",
    "notification_settings",
    "notifications",
    "plant_characters",
    "plant_diaries",
    "plant_environments",
    "plants",
    "species_care_guides",
    "species_identifications",
    "user_profiles",
)


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "ai_batch_jobs",
        sa.Column("job_type", sa.String(length=100), nullable=False),
        sa.Column("provider_batch_id", sa.String(length=255), nullable=True),
        sa.Column(
            "status", sa.String(length=16), server_default=sa.text("'CREATED'"), nullable=False
        ),
        sa.Column("input_file_id", sa.String(length=255), nullable=True),
        sa.Column("output_file_id", sa.String(length=255), nullable=True),
        sa.Column("total_count", sa.Integer(), server_default=sa.text("0"), nullable=False),
        sa.Column("completed_count", sa.Integer(), server_default=sa.text("0"), nullable=False),
        sa.Column("failed_count", sa.Integer(), server_default=sa.text("0"), nullable=False),
        sa.Column("error_code", sa.String(length=100), nullable=True),
        sa.Column("submitted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.CheckConstraint(
            "status IN ('CREATED', 'SUBMITTED', 'IN_PROGRESS', 'COMPLETED', 'FAILED', 'CANCELLED')",
            name=op.f("ck_ai_batch_jobs_status"),
        ),
        sa.CheckConstraint(
            "completed_count + failed_count <= total_count",
            name=op.f("ck_ai_batch_jobs_completed_counts"),
        ),
        sa.CheckConstraint(
            "total_count >= 0 AND completed_count >= 0 AND failed_count >= 0",
            name=op.f("ck_ai_batch_jobs_counts"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_ai_batch_jobs")),
        sa.UniqueConstraint("provider_batch_id", name=op.f("uq_ai_batch_jobs_provider_batch_id")),
    )
    op.create_index(
        "ix_ai_batch_jobs_status_created_at",
        "ai_batch_jobs",
        ["status", "created_at"],
        unique=False,
    )
    op.create_table(
        "species_care_guides",
        sa.Column("species_reference_id", sa.String(length=255), nullable=False),
        sa.Column("display_name", sa.String(length=200), nullable=False),
        sa.Column("scientific_name", sa.String(length=255), nullable=True),
        sa.Column("category", sa.String(length=32), nullable=False),
        sa.Column("recommended_water_min_ml", sa.Integer(), nullable=True),
        sa.Column("recommended_water_max_ml", sa.Integer(), nullable=True),
        sa.Column(
            "water_recommendation_source",
            sa.String(length=32),
            server_default=sa.text("'SPECIES_GUIDE'"),
            nullable=False,
        ),
        sa.Column("active", sa.Boolean(), server_default=sa.text("true"), nullable=False),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "category IN ('FOLIAGE', 'FLOWER', 'SUCCULENT_CACTUS', 'TREE', 'HERB', 'FRUIT', 'VINE')",
            name=op.f("ck_species_care_guides_category"),
        ),
        sa.CheckConstraint(
            "water_recommendation_source IN ('SPECIES_GUIDE')",
            name=op.f("ck_species_care_guides_water_recommendation_source"),
        ),
        sa.CheckConstraint(
            "(recommended_water_min_ml IS NULL AND recommended_water_max_ml IS NULL) OR (recommended_water_min_ml > 0 AND recommended_water_min_ml <= recommended_water_max_ml)",
            name=op.f("ck_species_care_guides_water_amount_range"),
        ),
        sa.PrimaryKeyConstraint("species_reference_id", name=op.f("pk_species_care_guides")),
    )
    op.create_index(
        "ix_species_care_guides_display_name", "species_care_guides", ["display_name"], unique=False
    )
    op.create_table(
        "device_tokens",
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("platform", sa.String(length=16), nullable=False),
        sa.Column("token", sa.String(length=4096), nullable=False),
        sa.Column("last_used_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("revoked_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.CheckConstraint(
            "platform IN ('IOS', 'ANDROID')", name=op.f("ck_device_tokens_platform")
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["auth.users.id"],
            name=op.f("fk_device_tokens_user_id_users"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_device_tokens")),
    )
    op.create_index(
        "ix_device_tokens_user_id_revoked_at",
        "device_tokens",
        ["user_id", "revoked_at"],
        unique=False,
    )
    op.create_index(
        "uq_device_tokens_active_token",
        "device_tokens",
        ["token"],
        unique=True,
        postgresql_where=sa.text("revoked_at IS NULL"),
    )
    op.create_table(
        "media_files",
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("purpose", sa.String(length=32), nullable=False),
        sa.Column(
            "status", sa.String(length=16), server_default=sa.text("'PENDING'"), nullable=False
        ),
        sa.Column("bucket_name", sa.String(length=100), nullable=False),
        sa.Column("object_path", sa.String(length=1024), nullable=False),
        sa.Column("content_type", sa.String(length=100), nullable=False),
        sa.Column("size_bytes", sa.BigInteger(), nullable=True),
        sa.Column("checksum_sha256", sa.String(length=64), nullable=True),
        sa.Column("width", sa.Integer(), nullable=True),
        sa.Column("height", sa.Integer(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.CheckConstraint(
            "purpose IN ('USER_PROFILE', 'PLANT_PROFILE', 'SPECIES_IDENTIFICATION', 'DIARY', 'DIAGNOSIS', 'CHAT')",
            name=op.f("ck_media_files_purpose"),
        ),
        sa.CheckConstraint(
            "status IN ('PENDING', 'READY', 'FAILED', 'DELETED')",
            name=op.f("ck_media_files_status"),
        ),
        sa.CheckConstraint("height IS NULL OR height > 0", name=op.f("ck_media_files_height")),
        sa.CheckConstraint(
            "size_bytes IS NULL OR size_bytes >= 0", name=op.f("ck_media_files_size_bytes")
        ),
        sa.CheckConstraint("width IS NULL OR width > 0", name=op.f("ck_media_files_width")),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["auth.users.id"],
            name=op.f("fk_media_files_user_id_users"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_media_files")),
        sa.UniqueConstraint("object_path", name=op.f("uq_media_files_object_path")),
    )
    op.create_index(
        "ix_media_files_user_id_status_created_at",
        "media_files",
        ["user_id", "status", "created_at"],
        unique=False,
    )
    op.create_table(
        "notification_settings",
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column(
            "care_reminder_enabled", sa.Boolean(), server_default=sa.text("true"), nullable=False
        ),
        sa.Column(
            "diagnosis_complete_enabled",
            sa.Boolean(),
            server_default=sa.text("true"),
            nullable=False,
        ),
        sa.Column(
            "monthly_report_enabled", sa.Boolean(), server_default=sa.text("true"), nullable=False
        ),
        sa.Column("quiet_hours_start", sa.Time(), nullable=True),
        sa.Column("quiet_hours_end", sa.Time(), nullable=True),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "(quiet_hours_start IS NULL) = (quiet_hours_end IS NULL)",
            name=op.f("ck_notification_settings_quiet_hours_pair"),
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["auth.users.id"],
            name=op.f("fk_notification_settings_user_id_users"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("user_id", name=op.f("pk_notification_settings")),
    )
    op.create_table(
        "user_profiles",
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("profile_media_file_id", sa.UUID(), nullable=True),
        sa.Column("nickname", sa.String(length=100), nullable=False),
        sa.Column("bio", sa.String(length=500), nullable=True),
        sa.Column(
            "timezone", sa.String(length=64), server_default=sa.text("'Asia/Seoul'"), nullable=False
        ),
        sa.Column("selected_plant_id", sa.UUID(), nullable=True),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["profile_media_file_id"],
            ["media_files.id"],
            name=op.f("fk_user_profiles_profile_media_file_id_media_files"),
            ondelete="SET NULL",
            use_alter=True,
        ),
        sa.ForeignKeyConstraint(
            ["selected_plant_id"],
            ["plants.id"],
            name=op.f("fk_user_profiles_selected_plant_id_plants"),
            ondelete="SET NULL",
            use_alter=True,
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["auth.users.id"],
            name=op.f("fk_user_profiles_user_id_users"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("user_id", name=op.f("pk_user_profiles")),
    )
    op.create_index(
        "ix_user_profiles_selected_plant_id", "user_profiles", ["selected_plant_id"], unique=False
    )
    op.create_table(
        "species_identifications",
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("media_file_id", sa.UUID(), nullable=False),
        sa.Column(
            "status", sa.String(length=16), server_default=sa.text("'PENDING'"), nullable=False
        ),
        sa.Column("provider", sa.String(length=100), nullable=True),
        sa.Column("candidates", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("failure_code", sa.String(length=100), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.CheckConstraint(
            "status IN ('PENDING', 'PROCESSING', 'COMPLETED', 'FAILED')",
            name=op.f("ck_species_identifications_status"),
        ),
        sa.ForeignKeyConstraint(
            ["media_file_id"],
            ["media_files.id"],
            name=op.f("fk_species_identifications_media_file_id_media_files"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["auth.users.id"],
            name=op.f("fk_species_identifications_user_id_users"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_species_identifications")),
    )
    op.create_table(
        "plants",
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("primary_media_file_id", sa.UUID(), nullable=True),
        sa.Column("species_identification_id", sa.UUID(), nullable=True),
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column("category", sa.String(length=32), nullable=False),
        sa.Column("species_name", sa.String(length=200), nullable=False),
        sa.Column("species_scientific_name", sa.String(length=255), nullable=True),
        sa.Column("species_reference_id", sa.String(length=255), nullable=False),
        sa.Column("species_selection_method", sa.String(length=16), nullable=False),
        sa.Column("started_on", sa.Date(), nullable=False),
        sa.Column("memo", sa.Text(), nullable=True),
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.CheckConstraint(
            "category IN ('FOLIAGE', 'FLOWER', 'SUCCULENT_CACTUS', 'TREE', 'HERB', 'FRUIT', 'VINE')",
            name=op.f("ck_plants_category"),
        ),
        sa.CheckConstraint(
            "species_selection_method IN ('SEARCH', 'PHOTO')",
            name=op.f("ck_plants_species_selection_method"),
        ),
        sa.ForeignKeyConstraint(
            ["primary_media_file_id"],
            ["media_files.id"],
            name=op.f("fk_plants_primary_media_file_id_media_files"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["species_identification_id"],
            ["species_identifications.id"],
            name=op.f("fk_plants_species_identification_id_species_identifications"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["user_id"], ["auth.users.id"], name=op.f("fk_plants_user_id_users"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_plants")),
        sa.UniqueConstraint(
            "species_identification_id", name=op.f("uq_plants_species_identification_id")
        ),
    )
    op.create_index(
        "ix_plants_user_id_deleted_at", "plants", ["user_id", "deleted_at"], unique=False
    )
    op.create_table(
        "ai_batch_items",
        sa.Column("batch_job_id", sa.UUID(), nullable=False),
        sa.Column("custom_id", sa.String(length=255), nullable=False),
        sa.Column("plant_id", sa.UUID(), nullable=False),
        sa.Column("target_year", sa.Integer(), nullable=False),
        sa.Column("target_month", sa.Integer(), nullable=False),
        sa.Column(
            "status", sa.String(length=16), server_default=sa.text("'PENDING'"), nullable=False
        ),
        sa.Column("result", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("error_code", sa.String(length=100), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.CheckConstraint(
            "status IN ('PENDING', 'PROCESSING', 'COMPLETED', 'FAILED')",
            name=op.f("ck_ai_batch_items_status"),
        ),
        sa.CheckConstraint(
            "target_month BETWEEN 1 AND 12", name=op.f("ck_ai_batch_items_target_month")
        ),
        sa.CheckConstraint("target_year >= 2000", name=op.f("ck_ai_batch_items_target_year")),
        sa.ForeignKeyConstraint(
            ["batch_job_id"],
            ["ai_batch_jobs.id"],
            name=op.f("fk_ai_batch_items_batch_job_id_ai_batch_jobs"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["plant_id"],
            ["plants.id"],
            name=op.f("fk_ai_batch_items_plant_id_plants"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_ai_batch_items")),
        sa.UniqueConstraint("custom_id", name=op.f("uq_ai_batch_items_custom_id")),
    )
    op.create_index(
        "ix_ai_batch_items_batch_job_id_status",
        "ai_batch_items",
        ["batch_job_id", "status"],
        unique=False,
    )
    op.create_table(
        "ai_chats",
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("plant_id", sa.UUID(), nullable=False),
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["plant_id"],
            ["plants.id"],
            name=op.f("fk_ai_chats_plant_id_plants"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["auth.users.id"],
            name=op.f("fk_ai_chats_user_id_users"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_ai_chats")),
        sa.UniqueConstraint("plant_id", name="uq_ai_chats_plant_id"),
    )
    op.create_table(
        "care_schedules",
        sa.Column("plant_id", sa.UUID(), nullable=False),
        sa.Column("type", sa.String(length=16), nullable=False),
        sa.Column("interval_days", sa.Integer(), nullable=False),
        sa.Column("next_due_date", sa.Date(), nullable=False),
        sa.Column("recommended_water_min_ml", sa.Integer(), nullable=True),
        sa.Column("recommended_water_max_ml", sa.Integer(), nullable=True),
        sa.Column("water_recommendation_source", sa.String(length=32), nullable=True),
        sa.Column("enabled", sa.Boolean(), server_default=sa.text("true"), nullable=False),
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "(recommended_water_min_ml IS NULL AND recommended_water_max_ml IS NULL) OR (type = 'WATERING' AND recommended_water_min_ml > 0 AND recommended_water_min_ml <= recommended_water_max_ml)",
            name=op.f("ck_care_schedules_water_amount_range"),
        ),
        sa.CheckConstraint(
            "type IN ('WATERING', 'REPOTTING')", name=op.f("ck_care_schedules_type")
        ),
        sa.CheckConstraint(
            "water_recommendation_source IS NULL OR water_recommendation_source IN ('SPECIES_GUIDE')",
            name=op.f("ck_care_schedules_water_recommendation_source"),
        ),
        sa.CheckConstraint("interval_days > 0", name=op.f("ck_care_schedules_interval_days")),
        sa.ForeignKeyConstraint(
            ["plant_id"],
            ["plants.id"],
            name=op.f("fk_care_schedules_plant_id_plants"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_care_schedules")),
        sa.UniqueConstraint("plant_id", "type", name="uq_care_schedules_plant_type"),
    )
    op.create_index(
        "ix_care_schedules_enabled_next_due_date",
        "care_schedules",
        ["enabled", "next_due_date"],
        unique=False,
    )
    op.create_table(
        "diagnoses",
        sa.Column("plant_id", sa.UUID(), nullable=False),
        sa.Column("related_conversation_id", sa.UUID(), nullable=True),
        sa.Column(
            "status", sa.String(length=20), server_default=sa.text("'PENDING'"), nullable=False
        ),
        sa.Column("overall_condition", sa.String(length=16), nullable=True),
        sa.Column("symptom_started_on", sa.Date(), nullable=True),
        sa.Column("input_context_snapshot", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("image_quality_result", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("user_note", sa.Text(), nullable=True),
        sa.Column("condition_label", sa.String(length=200), nullable=True),
        sa.Column("observations", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("possible_causes", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("recommended_care", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("retake_reason_code", sa.String(length=100), nullable=True),
        sa.Column("failure_code", sa.String(length=100), nullable=True),
        sa.Column("diagnosis_provider", sa.String(length=100), nullable=True),
        sa.Column("diagnosis_model_name", sa.String(length=200), nullable=True),
        sa.Column("diagnosis_provider_response_id", sa.String(length=255), nullable=True),
        sa.Column("explanation_provider", sa.String(length=100), nullable=True),
        sa.Column("explanation_model_name", sa.String(length=200), nullable=True),
        sa.Column("explanation_prompt_version", sa.String(length=100), nullable=True),
        sa.Column("care_rule_version", sa.String(length=100), nullable=True),
        sa.Column("diagnosis_latency_ms", sa.Integer(), nullable=True),
        sa.Column("estimated_cost", sa.Numeric(precision=12, scale=6), nullable=True),
        sa.Column("cost_currency", sa.String(length=3), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.CheckConstraint(
            "overall_condition IS NULL OR overall_condition IN ('HEALTHY', 'UNHEALTHY', 'UNCERTAIN')",
            name=op.f("ck_diagnoses_overall_condition"),
        ),
        sa.CheckConstraint(
            "possible_causes IS NULL OR (jsonb_typeof(possible_causes) = 'array' AND jsonb_array_length(possible_causes) <= 3)",
            name=op.f("ck_diagnoses_possible_causes"),
        ),
        sa.CheckConstraint(
            "status IN ('PENDING', 'PROCESSING', 'COMPLETED', 'NEEDS_RETAKE', 'FAILED', 'CANCELLED')",
            name=op.f("ck_diagnoses_status"),
        ),
        sa.CheckConstraint(
            "diagnosis_latency_ms IS NULL OR diagnosis_latency_ms >= 0",
            name=op.f("ck_diagnoses_diagnosis_latency_ms"),
        ),
        sa.CheckConstraint(
            "estimated_cost IS NULL OR estimated_cost >= 0",
            name=op.f("ck_diagnoses_estimated_cost"),
        ),
        sa.ForeignKeyConstraint(
            ["plant_id"],
            ["plants.id"],
            name=op.f("fk_diagnoses_plant_id_plants"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["related_conversation_id"],
            ["ai_conversations.id"],
            name=op.f("fk_diagnoses_related_conversation_id_ai_conversations"),
            ondelete="SET NULL",
            use_alter=True,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_diagnoses")),
    )
    op.create_index(
        "ix_diagnoses_plant_id_created_at",
        "diagnoses",
        ["plant_id", sa.literal_column("created_at DESC")],
        unique=False,
    )
    op.create_index(
        "ix_diagnoses_status_created_at", "diagnoses", ["status", "created_at"], unique=False
    )
    op.create_table(
        "notifications",
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("plant_id", sa.UUID(), nullable=True),
        sa.Column("type", sa.String(length=100), nullable=False),
        sa.Column("title", sa.String(length=200), nullable=False),
        sa.Column("body", sa.Text(), nullable=False),
        sa.Column("source_type", sa.String(length=100), nullable=True),
        sa.Column("source_id", sa.UUID(), nullable=True),
        sa.Column("read_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.ForeignKeyConstraint(
            ["plant_id"],
            ["plants.id"],
            name=op.f("fk_notifications_plant_id_plants"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["auth.users.id"],
            name=op.f("fk_notifications_user_id_users"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_notifications")),
    )
    op.create_index(
        "ix_notifications_user_id_read_at_created_at",
        "notifications",
        ["user_id", "read_at", sa.literal_column("created_at DESC")],
        unique=False,
    )
    op.create_table(
        "plant_characters",
        sa.Column("plant_id", sa.UUID(), nullable=False),
        sa.Column("base_type", sa.String(length=100), nullable=False),
        sa.Column("body_color", sa.String(length=100), nullable=False),
        sa.Column("head_item", sa.String(length=100), nullable=True),
        sa.Column("accessory", sa.String(length=100), nullable=True),
        sa.Column("personality_type", sa.String(length=32), nullable=False),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "personality_type IN ('OUTGOING', 'CHIC', 'CUTE', 'CRUSH', 'INTROVERTED', 'CHUNGCHEONG')",
            name=op.f("ck_plant_characters_personality_type"),
        ),
        sa.ForeignKeyConstraint(
            ["plant_id"],
            ["plants.id"],
            name=op.f("fk_plant_characters_plant_id_plants"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("plant_id", name=op.f("pk_plant_characters")),
    )
    op.create_table(
        "plant_diaries",
        sa.Column("plant_id", sa.UUID(), nullable=False),
        sa.Column("media_file_id", sa.UUID(), nullable=True),
        sa.Column("diary_date", sa.Date(), nullable=False),
        sa.Column("content", sa.Text(), nullable=False),
        sa.Column("condition_level", sa.String(length=16), nullable=False),
        sa.Column("condition_score", sa.Integer(), nullable=False),
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.CheckConstraint(
            "(condition_level = 'VERY_BAD' AND condition_score = 10) OR (condition_level = 'BAD' AND condition_score = 30) OR (condition_level = 'NORMAL' AND condition_score = 50) OR (condition_level = 'GOOD' AND condition_score = 70) OR (condition_level = 'VERY_GOOD' AND condition_score = 90)",
            name=op.f("ck_plant_diaries_condition_score_mapping"),
        ),
        sa.CheckConstraint(
            "condition_level IN ('VERY_BAD', 'BAD', 'NORMAL', 'GOOD', 'VERY_GOOD')",
            name=op.f("ck_plant_diaries_condition_level"),
        ),
        sa.ForeignKeyConstraint(
            ["media_file_id"],
            ["media_files.id"],
            name=op.f("fk_plant_diaries_media_file_id_media_files"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["plant_id"],
            ["plants.id"],
            name=op.f("fk_plant_diaries_plant_id_plants"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_plant_diaries")),
        sa.UniqueConstraint("plant_id", "diary_date", name="uq_plant_diaries_plant_date"),
    )
    op.create_index(
        "ix_plant_diaries_plant_id_diary_date",
        "plant_diaries",
        ["plant_id", sa.literal_column("diary_date DESC")],
        unique=False,
    )
    op.create_table(
        "plant_environments",
        sa.Column("plant_id", sa.UUID(), nullable=False),
        sa.Column("place_name", sa.String(length=100), nullable=False),
        sa.Column("pot_type", sa.String(length=100), nullable=True),
        sa.Column("placement", sa.String(length=100), nullable=True),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["plant_id"],
            ["plants.id"],
            name=op.f("fk_plant_environments_plant_id_plants"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("plant_id", name=op.f("pk_plant_environments")),
    )
    op.create_table(
        "ai_conversations",
        sa.Column("chat_id", sa.UUID(), nullable=False),
        sa.Column("title", sa.String(length=200), nullable=False),
        sa.Column("provider_conversation_id", sa.String(length=255), nullable=True),
        sa.Column("context_summary", sa.Text(), nullable=True),
        sa.Column("summarized_through_message_id", sa.UUID(), nullable=True),
        sa.Column("summary_version", sa.Integer(), server_default=sa.text("0"), nullable=False),
        sa.Column("summary_updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("last_message_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.CheckConstraint(
            "summary_version >= 0", name=op.f("ck_ai_conversations_summary_version")
        ),
        sa.ForeignKeyConstraint(
            ["chat_id"],
            ["ai_chats.id"],
            name=op.f("fk_ai_conversations_chat_id_ai_chats"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["summarized_through_message_id"],
            ["ai_messages.id"],
            name=op.f("fk_ai_conversations_summarized_through_message_id_ai_messages"),
            ondelete="SET NULL",
            use_alter=True,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_ai_conversations")),
    )
    op.create_index(
        "ix_ai_conversations_chat_id_last_message_at",
        "ai_conversations",
        ["chat_id", sa.literal_column("last_message_at DESC")],
        unique=False,
    )
    op.create_index(
        "ix_ai_conversations_chat_id_title", "ai_conversations", ["chat_id", "title"], unique=False
    )
    op.create_table(
        "care_events",
        sa.Column("plant_id", sa.UUID(), nullable=False),
        sa.Column("schedule_id", sa.UUID(), nullable=True),
        sa.Column("source_diagnosis_id", sa.UUID(), nullable=True),
        sa.Column("type", sa.String(length=16), nullable=False),
        sa.Column("title", sa.String(length=200), nullable=True),
        sa.Column(
            "status", sa.String(length=16), server_default=sa.text("'SCHEDULED'"), nullable=False
        ),
        sa.Column("scheduled_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("note", sa.Text(), nullable=True),
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "(type <> 'CUSTOM') OR (title IS NOT NULL AND schedule_id IS NULL)",
            name=op.f("ck_care_events_custom_event"),
        ),
        sa.CheckConstraint(
            "status IN ('SCHEDULED', 'OVERDUE', 'COMPLETED', 'CANCELLED')",
            name=op.f("ck_care_events_status"),
        ),
        sa.CheckConstraint(
            "type IN ('WATERING', 'REPOTTING', 'FERTILIZING', 'PRUNING', 'CUSTOM')",
            name=op.f("ck_care_events_type"),
        ),
        sa.ForeignKeyConstraint(
            ["plant_id"],
            ["plants.id"],
            name=op.f("fk_care_events_plant_id_plants"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["schedule_id"],
            ["care_schedules.id"],
            name=op.f("fk_care_events_schedule_id_care_schedules"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["source_diagnosis_id"],
            ["diagnoses.id"],
            name=op.f("fk_care_events_source_diagnosis_id_diagnoses"),
            ondelete="SET NULL",
            use_alter=True,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_care_events")),
    )
    op.create_index(
        "ix_care_events_plant_id_scheduled_at",
        "care_events",
        ["plant_id", "scheduled_at"],
        unique=False,
    )
    op.create_index(
        "ix_care_events_status_scheduled_at",
        "care_events",
        ["status", "scheduled_at"],
        unique=False,
    )
    op.create_table(
        "diagnosis_images",
        sa.Column("diagnosis_id", sa.UUID(), nullable=False),
        sa.Column("media_file_id", sa.UUID(), nullable=False),
        sa.ForeignKeyConstraint(
            ["diagnosis_id"],
            ["diagnoses.id"],
            name=op.f("fk_diagnosis_images_diagnosis_id_diagnoses"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["media_file_id"],
            ["media_files.id"],
            name=op.f("fk_diagnosis_images_media_file_id_media_files"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("diagnosis_id", name=op.f("pk_diagnosis_images")),
    )
    op.create_table(
        "monthly_reports",
        sa.Column("plant_id", sa.UUID(), nullable=False),
        sa.Column("batch_item_id", sa.UUID(), nullable=True),
        sa.Column("report_year", sa.Integer(), nullable=False),
        sa.Column("report_month", sa.Integer(), nullable=False),
        sa.Column(
            "status", sa.String(length=16), server_default=sa.text("'PENDING'"), nullable=False
        ),
        sa.Column("average_condition_score", sa.Integer(), nullable=True),
        sa.Column("condition_summary", sa.Text(), nullable=True),
        sa.Column("care_summary", sa.Text(), nullable=True),
        sa.Column("frequent_issues", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column(
            "next_month_recommendations", postgresql.JSONB(astext_type=sa.Text()), nullable=True
        ),
        sa.Column("model_name", sa.String(length=200), nullable=True),
        sa.Column("prompt_version", sa.String(length=100), nullable=True),
        sa.Column("generated_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "status IN ('PENDING', 'COMPLETED', 'FAILED')", name=op.f("ck_monthly_reports_status")
        ),
        sa.CheckConstraint(
            "average_condition_score IS NULL OR average_condition_score BETWEEN 0 AND 100",
            name=op.f("ck_monthly_reports_average_condition_score"),
        ),
        sa.CheckConstraint(
            "report_month BETWEEN 1 AND 12", name=op.f("ck_monthly_reports_report_month")
        ),
        sa.CheckConstraint("report_year >= 2000", name=op.f("ck_monthly_reports_report_year")),
        sa.ForeignKeyConstraint(
            ["batch_item_id"],
            ["ai_batch_items.id"],
            name=op.f("fk_monthly_reports_batch_item_id_ai_batch_items"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["plant_id"],
            ["plants.id"],
            name=op.f("fk_monthly_reports_plant_id_plants"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_monthly_reports")),
        sa.UniqueConstraint("batch_item_id", name=op.f("uq_monthly_reports_batch_item_id")),
        sa.UniqueConstraint(
            "plant_id", "report_year", "report_month", name="uq_monthly_reports_plant_year_month"
        ),
    )
    op.create_index(
        "ix_monthly_reports_plant_id_year_month",
        "monthly_reports",
        ["plant_id", sa.literal_column("report_year DESC"), sa.literal_column("report_month DESC")],
        unique=False,
    )
    op.create_table(
        "ai_messages",
        sa.Column("conversation_id", sa.UUID(), nullable=False),
        sa.Column("related_diagnosis_id", sa.UUID(), nullable=True),
        sa.Column("media_file_id", sa.UUID(), nullable=True),
        sa.Column("role", sa.String(length=16), nullable=False),
        sa.Column(
            "status", sa.String(length=16), server_default=sa.text("'COMPLETED'"), nullable=False
        ),
        sa.Column("content", sa.Text(), nullable=False),
        sa.Column("provider", sa.String(length=100), nullable=True),
        sa.Column("model_name", sa.String(length=200), nullable=True),
        sa.Column("provider_response_id", sa.String(length=255), nullable=True),
        sa.Column("input_tokens", sa.Integer(), nullable=True),
        sa.Column("output_tokens", sa.Integer(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.CheckConstraint(
            "role IN ('USER', 'ASSISTANT', 'SYSTEM')", name=op.f("ck_ai_messages_role")
        ),
        sa.CheckConstraint(
            "status IN ('PENDING', 'PROCESSING', 'COMPLETED', 'FAILED')",
            name=op.f("ck_ai_messages_status"),
        ),
        sa.CheckConstraint(
            "input_tokens IS NULL OR input_tokens >= 0", name=op.f("ck_ai_messages_input_tokens")
        ),
        sa.CheckConstraint(
            "output_tokens IS NULL OR output_tokens >= 0", name=op.f("ck_ai_messages_output_tokens")
        ),
        sa.ForeignKeyConstraint(
            ["conversation_id"],
            ["ai_conversations.id"],
            name=op.f("fk_ai_messages_conversation_id_ai_conversations"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["media_file_id"],
            ["media_files.id"],
            name=op.f("fk_ai_messages_media_file_id_media_files"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["related_diagnosis_id"],
            ["diagnoses.id"],
            name=op.f("fk_ai_messages_related_diagnosis_id_diagnoses"),
            ondelete="SET NULL",
            use_alter=True,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_ai_messages")),
    )
    op.create_index(
        "ix_ai_messages_conversation_id_created_at",
        "ai_messages",
        ["conversation_id", "created_at"],
        unique=False,
    )
    op.create_table(
        "ai_actions",
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("message_id", sa.UUID(), nullable=False),
        sa.Column("plant_id", sa.UUID(), nullable=False),
        sa.Column("action_type", sa.String(length=100), nullable=False),
        sa.Column("payload", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column(
            "status",
            sa.String(length=32),
            server_default=sa.text("'PENDING_CONFIRMATION'"),
            nullable=False,
        ),
        sa.Column("version", sa.Integer(), server_default=sa.text("1"), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("confirmed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("executed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.CheckConstraint(
            "status IN ('PENDING_CONFIRMATION', 'EXECUTING', 'COMPLETED', 'CANCELLED', 'EXPIRED', 'FAILED')",
            name=op.f("ck_ai_actions_status"),
        ),
        sa.CheckConstraint("version > 0", name=op.f("ck_ai_actions_version")),
        sa.ForeignKeyConstraint(
            ["message_id"],
            ["ai_messages.id"],
            name=op.f("fk_ai_actions_message_id_ai_messages"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["plant_id"],
            ["plants.id"],
            name=op.f("fk_ai_actions_plant_id_plants"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["auth.users.id"],
            name=op.f("fk_ai_actions_user_id_users"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_ai_actions")),
    )
    op.create_index(
        "ix_ai_actions_user_id_status_expires_at",
        "ai_actions",
        ["user_id", "status", "expires_at"],
        unique=False,
    )
    op.create_table(
        "ai_tool_calls",
        sa.Column("message_id", sa.UUID(), nullable=False),
        sa.Column("provider_call_id", sa.String(length=255), nullable=False),
        sa.Column("tool_name", sa.String(length=100), nullable=False),
        sa.Column("arguments", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("result_summary", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column(
            "status", sa.String(length=16), server_default=sa.text("'PENDING'"), nullable=False
        ),
        sa.Column("latency_ms", sa.Integer(), nullable=True),
        sa.Column("error_code", sa.String(length=100), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.CheckConstraint(
            "status IN ('PENDING', 'COMPLETED', 'FAILED')", name=op.f("ck_ai_tool_calls_status")
        ),
        sa.CheckConstraint(
            "latency_ms IS NULL OR latency_ms >= 0", name=op.f("ck_ai_tool_calls_latency_ms")
        ),
        sa.ForeignKeyConstraint(
            ["message_id"],
            ["ai_messages.id"],
            name=op.f("fk_ai_tool_calls_message_id_ai_messages"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_ai_tool_calls")),
        sa.UniqueConstraint("provider_call_id", name=op.f("uq_ai_tool_calls_provider_call_id")),
    )
    op.create_index(
        "ix_ai_tool_calls_message_id_created_at",
        "ai_tool_calls",
        ["message_id", "created_at"],
        unique=False,
    )
    op.create_foreign_key(
        "fk_user_profiles_profile_media_file_id_media_files",
        "user_profiles",
        "media_files",
        ["profile_media_file_id"],
        ["id"],
        ondelete="SET NULL",
    )
    op.create_foreign_key(
        "fk_user_profiles_selected_plant_id_plants",
        "user_profiles",
        "plants",
        ["selected_plant_id"],
        ["id"],
        ondelete="SET NULL",
    )
    op.create_foreign_key(
        "fk_diagnoses_related_conversation_id_ai_conversations",
        "diagnoses",
        "ai_conversations",
        ["related_conversation_id"],
        ["id"],
        ondelete="SET NULL",
    )
    op.create_foreign_key(
        "fk_ai_conversations_summarized_through_message_id_ai_messages",
        "ai_conversations",
        "ai_messages",
        ["summarized_through_message_id"],
        ["id"],
        ondelete="SET NULL",
    )
    op.create_foreign_key(
        "fk_care_events_source_diagnosis_id_diagnoses",
        "care_events",
        "diagnoses",
        ["source_diagnosis_id"],
        ["id"],
        ondelete="SET NULL",
    )
    op.create_foreign_key(
        "fk_ai_messages_related_diagnosis_id_diagnoses",
        "ai_messages",
        "diagnoses",
        ["related_diagnosis_id"],
        ["id"],
        ondelete="SET NULL",
    )

    # The mobile client never accesses application tables through the Data API.
    # Enabling RLS without client policies keeps anon/authenticated roles denied.
    for table_name in RLS_TABLES:
        op.execute(f'ALTER TABLE public."{table_name}" ENABLE ROW LEVEL SECURITY')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        "fk_ai_messages_related_diagnosis_id_diagnoses",
        "ai_messages",
        type_="foreignkey",
    )
    op.drop_constraint(
        "fk_care_events_source_diagnosis_id_diagnoses",
        "care_events",
        type_="foreignkey",
    )
    op.drop_constraint(
        "fk_ai_conversations_summarized_through_message_id_ai_messages",
        "ai_conversations",
        type_="foreignkey",
    )
    op.drop_constraint(
        "fk_diagnoses_related_conversation_id_ai_conversations",
        "diagnoses",
        type_="foreignkey",
    )
    op.drop_constraint(
        "fk_user_profiles_selected_plant_id_plants",
        "user_profiles",
        type_="foreignkey",
    )
    op.drop_constraint(
        "fk_user_profiles_profile_media_file_id_media_files",
        "user_profiles",
        type_="foreignkey",
    )
    op.drop_index("ix_ai_tool_calls_message_id_created_at", table_name="ai_tool_calls")
    op.drop_table("ai_tool_calls")
    op.drop_index("ix_ai_actions_user_id_status_expires_at", table_name="ai_actions")
    op.drop_table("ai_actions")
    op.drop_index("ix_ai_messages_conversation_id_created_at", table_name="ai_messages")
    op.drop_table("ai_messages")
    op.drop_index("ix_monthly_reports_plant_id_year_month", table_name="monthly_reports")
    op.drop_table("monthly_reports")
    op.drop_table("diagnosis_images")
    op.drop_index("ix_care_events_status_scheduled_at", table_name="care_events")
    op.drop_index("ix_care_events_plant_id_scheduled_at", table_name="care_events")
    op.drop_table("care_events")
    op.drop_index("ix_ai_conversations_chat_id_title", table_name="ai_conversations")
    op.drop_index("ix_ai_conversations_chat_id_last_message_at", table_name="ai_conversations")
    op.drop_table("ai_conversations")
    op.drop_table("plant_environments")
    op.drop_index("ix_plant_diaries_plant_id_diary_date", table_name="plant_diaries")
    op.drop_table("plant_diaries")
    op.drop_table("plant_characters")
    op.drop_index("ix_notifications_user_id_read_at_created_at", table_name="notifications")
    op.drop_table("notifications")
    op.drop_index("ix_diagnoses_status_created_at", table_name="diagnoses")
    op.drop_index("ix_diagnoses_plant_id_created_at", table_name="diagnoses")
    op.drop_table("diagnoses")
    op.drop_index("ix_care_schedules_enabled_next_due_date", table_name="care_schedules")
    op.drop_table("care_schedules")
    op.drop_table("ai_chats")
    op.drop_index("ix_ai_batch_items_batch_job_id_status", table_name="ai_batch_items")
    op.drop_table("ai_batch_items")
    op.drop_index("ix_plants_user_id_deleted_at", table_name="plants")
    op.drop_table("plants")
    op.drop_table("species_identifications")
    op.drop_index("ix_user_profiles_selected_plant_id", table_name="user_profiles")
    op.drop_table("user_profiles")
    op.drop_table("notification_settings")
    op.drop_index("ix_media_files_user_id_status_created_at", table_name="media_files")
    op.drop_table("media_files")
    op.drop_index(
        "uq_device_tokens_active_token",
        table_name="device_tokens",
        postgresql_where=sa.text("revoked_at IS NULL"),
    )
    op.drop_index("ix_device_tokens_user_id_revoked_at", table_name="device_tokens")
    op.drop_table("device_tokens")
    op.drop_index("ix_species_care_guides_display_name", table_name="species_care_guides")
    op.drop_table("species_care_guides")
    op.drop_index("ix_ai_batch_jobs_status_created_at", table_name="ai_batch_jobs")
    op.drop_table("ai_batch_jobs")
    # ### end Alembic commands ###
